sudo: required
services:
  - docker
before_script:
  - docker run -d -p 27017:27017 --name mongodb mongo
  - docker build -t powergrid .
script:
  - docker run -it --link mongodb -e "POWERGRID_DATABASE=mongodb://mongodb:27017/powergrid_travis" powergrid gulp test
